### YamlMime:PowershellCmdlet
summary: |-
  {{ Fill in the Synopsis }}
module: Gatewaytunnel
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#GatewayConfigurationObject" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-GatewayConfiguration [-RoutingDomainName <String>] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>]
   [-AsJob] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    {{ Fill AsJob Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Management.Infrastructure.CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    {{ Fill CimSession Description }}

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: RoutingDomainName
  description: |+
    {{ Fill RoutingDomainName Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: customer
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    {{ Fill ThrottleLimit Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Gatewaytunnel.Get-GatewayConfiguration
name: Get-GatewayConfiguration
description: |-
  {{ Fill in the Description }}
metadata:
  external help file: GatewayConfig_v1.0.cdxml-help.xml
  Module Name: Gatewaytunnel
  ms.date: 02/21/2024
  online version: https://learn.microsoft.com/powershell/module/gatewaytunnel/get-gatewayconfiguration?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  PlatyPS schema version: 2.0.0
  title: Get-GatewayConfiguration
